name: flutter_application_1
description: Aplicación de Caja Fuerte Segura con autenticación biométrica
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Paquetes CRÍTICOS (versiones compatibles probadas)
  biometric_storage: ^5.0.1  # Versión que soporta win32 5.x
  file_picker: ^6.1.1        # Compatible con biometric_storage 5.x
  cryptography: ^2.6.0       # Para AES-256-GCM

  # Dependencias complementarias
  path_provider: ^2.1.1
  share_plus: ^6.3.0         # Compatible con file_picker 6.x
  local_auth: ^2.1.8         # Autenticación biométrica
  flutter_secure_storage: ^8.0.0
  uuid: ^4.2.0
  intl: ^0.18.1              # Formateo de fechas
  flutter_windowmanager: ^0.2.0 # Bloqueo de pantalla

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

